
image: registry.gitlab.com/liquiduniverse/docgen:latest

stages:
 #- build
 #- test
 #- pages
 - update-parent


#before_script:
 #- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

#build:
  #stage: build
  #script:
   #- dotnet build 
  
  #artifacts:    
   #paths:
    #- ./build/
  #tags:


# test stage (running the HyperionApiClient.UnitTests-project)
#test:
 #stage: test
 #script:
   #- dotnet test HyperionApiClientUnitTests/HyperionApiClientUnitTests.csproj


# pages stage (to create the html content, the GitBook-documentation)
#pages:
  #stage: pages
 # script:
    
    #- doxygen documentation/doxygen/Doxyfile
    #- doxybook2 --input documentation/doxyoutput/xml -#-output  documentation/gitbook --config documentation/#doxybook-config/gitbook/.doxybook/config.json -#-summary-input documentation/doxybook-config/gitbook/#SUMMARY.md.tmpl --summary-output documentation/gitbook/#SUMMARY.md 
    
    #- gitbook build documentation/gitbook public
  
  #artifacts:
   # paths:
     # - public
      #- documentation
  
update-parent:
  stage: update-parent
  script:
    
    - git clone https://ashleewawa17:Gamedesignerlee1@gitlab.com/ashleewawa17/wax-developer
    - cp gitbook_output ./wax-developer/documentation/gitbook_output
    - cd wax-developer
    - git add .
    - git commit -m"Updating"
    - git push
    



