image: registry.gitlab.com/liquiduniverse/docgen:latest

stages:
  - build
  - test
  - pages

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

# build stage
build:
  stage: build
  script:
    - chmod 777 build.sh && ./build.sh
  artifacts:
    paths:
      - ./build/
  tags:

# test stage (running the HyperionApiClient.UnitTests-project)
test:
  stage: test
  script:
      - echo "do nothing"








# pages stage (to create the html content, the GitBook-documentation)
pages:
  stage: pages
  script:
  - ./scripts/abidiffs/make_abidiff.sh
  - doxygen documentation/doxygen/Doxyfile
  - doxybook2 --input documentation/doxygen_output/xml --output documentation/vuepress --config documentation/doxybook/configs/vuepress/.doxybook/config.json
  - cd documentation/vuepress/
  - vuepress build
  - cp -r ./.vuepress/dist ../../public/develop
  artifacts:
    paths:
    - public
    - documentation
